/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SingletonFactory } from "./SingletonFactory";
export * as factories from "./factories";
export { SingletonFactory__factory } from "./factories/SingletonFactory__factory";
